DELETE FROM dispatch_zones;

INSERT INTO dispatch_zones (name, region) VALUES
('Central Hub', 'Dhaka'),
('Dhaka - Z01 Uttara North', 'Dhaka'),
('Dhaka - Z02 Uttara South', 'Dhaka'),
('Dhaka - Z03 Mirpur North', 'Dhaka'),
('Dhaka - Z04 Mirpur Central', 'Dhaka'),
('Dhaka - Z05 Mirpur South', 'Dhaka'),
('Dhaka - Z06 Mohammadpur', 'Dhaka'),
('Dhaka - Z07 Dhanmondi', 'Dhaka'),
('Dhaka - Z08 Tejgaon', 'Dhaka'),
('Dhaka - Z09 Gulshan', 'Dhaka'),
('Dhaka - Z10 Badda', 'Dhaka'),
('Dhaka - Z11 Cantonment', 'Dhaka'),
('Dhaka - Z12 Baridhara-Kuril', 'Dhaka'),
('Dhaka - Z13 Ramna', 'Dhaka'),
('Dhaka - Z14 Motijheel', 'Dhaka'),
('Dhaka - Z15 Old Dhaka North', 'Dhaka'),
('Dhaka - Z16 Old Dhaka South', 'Dhaka'),
('Dhaka - Z17 Jatrabari', 'Dhaka'),
('Dhaka - Z18 Kamrangirchar', 'Dhaka'),
('Dhaka - Z19 Khilgaon-Basabo', 'Dhaka'),
('Dhaka - Z20 Demra', 'Dhaka'),
('Faridpur', 'Dhaka'), ('Gazipur', 'Dhaka'), ('Gopalganj', 'Dhaka'), ('Kishoreganj', 'Dhaka'), ('Madaripur', 'Dhaka'), ('Manikganj', 'Dhaka'), ('Munshiganj', 'Dhaka'), ('Narayanganj', 'Dhaka'), ('Narsingdi', 'Dhaka'), ('Rajbari', 'Dhaka'), ('Shariatpur', 'Dhaka'), ('Tangail', 'Dhaka'),
('Bogra', 'Rajshahi'), ('Joypurhat', 'Rajshahi'), ('Naogaon', 'Rajshahi'), ('Natore', 'Rajshahi'), ('Nawabganj', 'Rajshahi'), ('Pabna', 'Rajshahi'), ('Rajshahi', 'Rajshahi'), ('Sirajganj', 'Rajshahi'),
('Dinajpur', 'Rangpur'), ('Gaibandha', 'Rangpur'), ('Kurigram', 'Rangpur'), ('Lalmonirhat', 'Rangpur'), ('Nilphamari', 'Rangpur'), ('Panchagarh', 'Rangpur'), ('Rangpur', 'Rangpur'), ('Thakurgaon', 'Rangpur'),
('Barguna', 'Barisal'), ('Barisal', 'Barisal'), ('Bhola', 'Barisal'), ('Jhalokati', 'Barisal'), ('Patuakhali', 'Barisal'), ('Pirojpur', 'Barisal'),
('Bandarban', 'Chattogram'), ('Brahmanbaria', 'Chattogram'), ('Chandpur', 'Chattogram'), ('Chattogram', 'Chattogram'), ('Cumilla', 'Chattogram'), ('Cox''s Bazar', 'Chattogram'), ('Feni', 'Chattogram'), ('Khagrachari', 'Chattogram'), ('Lakshmipur', 'Chattogram'), ('Noakhali', 'Chattogram'), ('Rangamati', 'Chattogram'),
('Habiganj', 'Sylhet'), ('Moulvibazar', 'Sylhet'), ('Sunamganj', 'Sylhet'), ('Sylhet', 'Sylhet'),
('Bagerhat', 'Khulna'), ('Chuadanga', 'Khulna'), ('Jashore', 'Khulna'), ('Jhenaidah', 'Khulna'), ('Khulna', 'Khulna'), ('Kushtia', 'Khulna'), ('Magura', 'Khulna'), ('Meherpur', 'Khulna'), ('Narail', 'Khulna'), ('Satkhira', 'Khulna'),
('Jamalpur', 'Mymensingh'), ('Mymensingh', 'Mymensingh'), ('Netrokona', 'Mymensingh'), ('Sherpur', 'Mymensingh');
